### ISSUE TITLE
Figured out pull request error

### ISSUE THREAD

**Issue by KingNero6** [KingNero6/Hardweare-TC-mod-#10]
I figured out the pull request error. I think because of all the changes in the file it must have triggered some kind of safety algorithm.

**Comment by pokmon987** [comment]
Ah, okay... I was thinking of deleting that repository and making a new fork, because I think a file name change kinda messed it up

**Comment by KingNero6** [comment]
Yeah I was just up all night and only got 4 hours of sleep so I will take care of it tomorrow.

**Comment by KingNero6** [comment]
Unless if you wonna delete it? Then go ahead.

**Comment by pokmon987** [comment]
Yeah, aight, I might
