### ISSUE TITLE
Minor glitch

### ISSUE THREAD

**Issue by KingNero6** [KingNero6/Hardweare-TC-mod-#3]
I think I know what is holding me up. When I pushed the button on merge pull request with repo, I have poor eyesight, it was the end of the day, and I pushed revert instead. Then it would not let me merge the pull request. so it reverted the code back 24 hours from 2 days ago. I have spent 3 days trying to fix it including today. I think I have it mostly fixed but I was wondering if y'all could take a quick look at the code a tell me if there is anything wrong.

**Comment by pokmon987** [comment]
I believe that pull request should fix the few errors there were

**Comment by KingNero6** [comment]
Well I completed the pull request and went through code for 30 mins with a fine tooth comb. I am wondering if something else is causing the game engine not to read my mod; Such as the following if there is a incampatible mod, or maybe there is some kind of issue with the game on the devs end. What do you think?

**Comment by KingNero6** [comment]
You know sometimes in my expirence, I have to restart an entire script. Sometimes it does not matter what is done, the error will never be corrected. I found this out when prgramming shaders in Unity and Making bluprints in Unreal Engine. so as a team memember, you have a vote in this decision. I know how much work we put into this. I don't want to restart my work which is why I am putting this up to vote. It won't take more than a day to rewrite the script. However I go whichever way the group goes.

**Comment by pokmon987** [comment]
It's still causing issues? I'm not sure why, it works perfectly fine for me... If you insist on rewriting it, you can, but I'm not sure that you'd have to. I have the script and it works fine for me, if you'd like me to send a pull request with the whole script to hopefully fix it

**Comment by KingNero6** [comment]
Okay I don't want to rewrite and I don't know why it is causing an issue. Could be so kind as to do a quick pull request?  I really don't know why it is causing me issues. what mods are you using?

**Comment by KingNero6** [comment]
Turns out it was pickin up another mod's error message.

**Comment by KingNero6** [comment]
I am closing this issue it is now solved.
