### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by KingNero6** [KingNero6/Hardweare-TC-mod-#5]
I was wondering are the printer and assocciated features showing up on your software desgin menue? If so what month are they showing up? We fixed the error but I am wondering if printer options are showing up on your end.

**Comment by pokmon987** [comment]
Oh, it's fixed now? Sorry, it got pretty late last night and I wasn't able to send a pull request. I'm unable to check right now, but I'll see as soon as I can

**Comment by KingNero6** [comment]
Cool thanks. Yeah it is fixed. It turns out the error was from another mod and the game engine was mixing the two mods up.

**Comment by pokmon987** [comment]
Ah, okay

**Comment by KingNero6** [comment]
To make it easier to coordinate out dev efforts I created a hardware mod dev group. Would you be so kind as to send me a link to your profile so I can send you a request to join the group?

**Comment by pokmon987** [comment]
Steam profile?

**Comment by KingNero6** [comment]
Yeah what is your steam name and icon?

**Comment by pokmon987** [comment]
Steam name is VuTuRs and the icon is a pixelated swirl

**Comment by KingNero6** [comment]
thanks

**Comment by KingNero6** [comment]
I will have to invite you to my firend list first. My name is mab with a frigate as a avatar

**Comment by KingNero6** [comment]
So, anyway, back to the question, did you see the printer and following options in the software dev menu?

**Comment by pokmon987** [comment]
I did see them, yes, but I had to modify the code a little bit

**Comment by KingNero6** [comment]
Could you do a quick pull request? and after class I can intergrate the code into the master branch. Thank you.

**Comment by KingNero6** [comment]
I tried merging your pull request but it says there is some kind of issue about a changed file and it won't merge automatically. I tried folling the intsructions and I tried following some web instrustions I found. I am sorry about this issue. I am sure reload the .git file to the pull request will resove the issue.

**Comment by KingNero6** [comment]
By the way don't worry I solved the issue. I

**Comment by pokmon987** [comment]
Oh, okay, sorry, in class

**Comment by KingNero6** [comment]
that is okay. I am finishing college next semister (the fall). and It turns out the code did not work and good luck with class.

**Comment by KingNero6** [comment]
Hey I am in now hurry to have this fixed. However, I would like to be able to sync the pull request. I have attempted to use git shell to force sync it. Also, I attempted to automatically repair the sync problem with the commands it suggested. I assume you need a different .git file for school. Just, when you get a chance, could you be so kind as to reupload the .git file?

**Comment by pokmon987** [comment]
Sorry, what exactly happened? I'm not very good with GitHub, you want me to reupload and try to send another pull request??

**Comment by pokmon987** [comment]
I'm really not sure why it won't merge. I just tried making another pull request with the error "Can't merge automatically". Could you make a new branch maybe?

**Comment by KingNero6** [comment]
I merged the pull request and now this issue is closed until the end of vacation on sunday.

**Comment by KingNero6** [comment]
Yeah could you make another pull request? and I don't know what happend. I am new to github myself. I got introduced to it from another team of modders a couple of years ago.

**Comment by KingNero6** [comment]
also I thought I solved the issue but it looks like it didn't sync.

**Comment by pokmon987** [comment]
Have you fixed it now? I sent a few pull requests, but it wouldn't allow me to send it to the main branch.

**Comment by KingNero6** [comment]
Well I am not sure it synced or not but it looks like it correced the issues after I merged the pull reqests. Also it is now showing up in the mod selection menu. Also the error message no longer displays. However, it still does not display printers on my computer.

**Comment by KingNero6** [comment]
It displays the standard software typs but not the printers

**Comment by KingNero6** [comment]
by the way I am just going to enter changes mannually tomorrow thank you for your time.
