### ISSUE TITLE
Pull reqest

### ISSUE THREAD

**Issue by KingNero6** [KingNero6/Hardweare-TC-mod-#8]
Hey pokomon I was wondering if you could create a new pull request with the code but a different script? I finished finals sooner than I antcipated so I have some extra time to kill.

**Comment by KingNero6** [comment]
oh and please make sure you put it on the master branch

**Comment by pokmon987** [comment]
Still isn't fixed? I'll try soon, my sister's friend is over and they're both using the computers at my house

**Comment by KingNero6** [comment]
that's okay take as much time as you need.

**Comment by KingNero6** [comment]
and thank you so much

**Comment by KingNero6** [comment]
by the way if this attempt at a pull request does not work than I will add the changes manually.
